version: '2'
services:
  nginx:
    build:
      context: ./deployment/nginx
    volumes:
      - ./:/var/www/lunchnlearn
      - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./deployment/nginx/sites-available/:/etc/nginx/sites-available
      - ./deployment/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8080:80"
    links:
      - php

  php:
    build:
      context: ./deployment/php
    volumes:
      - ./:/var/www/lunchnlearn
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
    links:
      - mysql

  mysql:
    build:
      context: ./deployment/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=lunchnlearn_app
      - MYSQL_USER=lunchnlearn_user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=docker